export const WORDS = [
  "Abanico", "Aceite", "Acero", "Acordeón", "Acuario", "Adaptador", "Adorno", "Afeitadora", "Aguacate", "Aguja",
  "Ajedrez", "Alfombra", "Almohada", "Altavoz", "Ambulancia", "Ancla", "Anillo", "Antena", "Antorcha", "Anzuelo",
  "Aparato", "Aspiradora", "Ataúd", "Atlas", "Atún", "Autobús", "Automóvil", "Avión", "Azúcar", "Azulejo",
  "Balón", "Banco", "Bandera", "Bañera", "Barco", "Barra", "Barril", "Batería", "Bicicleta", "Billete",
  "Binoculares", "Bisturí", "Bloque", "Blusa", "Bolígrafo", "Bolsa", "Bolsillo", "Bomba", "Bombilla",
  "Bota", "Botella", "Botón", "Boya", "Brazalete", "Brújula", "Burbuja", "Butaca", "Caballete", "Cabaña",
  "Cable", "Cadena", "Caja", "Cajón", "Calcetín", "Calculadora", "Caldera", "Calendario", "Cáliz", "Cama",
  "Cámara", "Camilla", "Camión", "Camiseta", "Campana", "Canasta", "Candado", "Candelabro", "Canoa", "Cañón",
  "Capa", "Capucha", "Cara", "Caramelo", "Carpa", "Carpeta", "Carretilla", "Carro", "Carta", "Cartera",
  "Cartón", "Casco", "Castillo", "Catenaria", "Cebolla", "Cedazo", "Celular", "Cenicero", "Cepillo", "Cerca",
  "Cereza", "Cerveza", "Cesta", "Cetro", "Chaqueta", "Cheque", "Chimenea", "Chupete", "Ciclomotor", "Cilindro",
  "Cincel", "Cinta", "Cinturón", "Clarinete", "Clavo", "Clip", "Coche", "Cocina", "Cofre", "Cohete",
  "Colchón", "Collar", "Columpio", "Cometa", "Computadora", "Condensador", "Conejo", "Copa", "Corbata", "Cordón",
  "Corona", "Cortina", "Cuchara", "Cuchillo", "Cuerda", "Cuerno", "Cuaderno", "Cuadro", "Cubo", "Cuna",
  "Dados", "Daga", "Dardo", "Delantal", "Detergente", "Diamante", "Diario", "Diccionario", "Diente", "Dinero",
  "Disco", "Disquete", "Diván", "Dominó", "Ducha", "Duende", "Dulce", "Edificio", "Eje", "Elástico",
  "Embudo", "Emparedado", "Enchufe", "Enciclopedia", "Engranaje", "Ensalada", "Escalera", "Escoba", "Escorpión", "Escritorio",
  "Escudo", "Esfera", "Espejo", "Esponja", "Esqueleto", "Estante", "Estatua", "Estetoscopio", "Estribo", "Estuche",
  "Etiqueta", "Extintor", "Falda", "Faro", "Flecha", "Flauta", "Florero", "Foco", "Folleto", "Fonógrafo",
  "Frasco", "Freno", "Fuente", "Fusil", "Gafas", "Gaita", "Galleta", "Gancho", "Garrafa", "Gato",
  "Globo", "Goma", "Gorro", "Grifo", "Grúa", "Guante", "Guitarra", "Hacha", "Hamaca", "Harina",
  "Hebilla", "Helado", "Helicóptero", "Hélice", "Hierro", "Hilo", "Hoja", "Horca", "Horno", "Hospital",
  "Huevo", "Imán", "Impresora", "Inodoro", "Insignia", "Instrumento", "Interruptor", "Invernadero", "Jabón", "Jaula",
  "Jarra", "Jeringa", "Joyero", "Juguete", "Ladrillo", "Lámpara", "Lanza", "Lápiz", "Lata", "Látigo",
  "Lazo", "Leche", "Lente", "Lenteja", "Letrero", "Libreta", "Libro", "Lija", "Lima", "Limón",
  "Linterna", "Llanta", "Llave", "Llavero", "Lona", "Lupa", "Luz", "Maceta", "Machete", "Maleta",
  "Malla", "Mancuerna", "Manguera", "Manivela", "Manzana", "Mapa", "Máquina", "Marco", "Martillo", "Máscara",
  "Mazo", "Medalla", "Megáfono", "Melón", "Memoria", "Mesa", "Metrónomo", "Microchip", "Micrófono", "Microscopio",
  "Mochila", "Molde", "Molino", "Moneda", "Monitor", "Monopatín", "Mopa", "Mortero", "Motor", "Mueble",
  "Muleta", "Muñeca", "Muro", "Museo", "Naranja", "Navaja", "Nave", "Neumático", "Nivel", "Nudo",
  "Obelisco", "Objetivo", "Olla", "Órgano", "Oro", "Ovillo", "Pala", "Palacio", "Palanca", "Paleta",
  "Palillo", "Palmera", "Pan", "Pandereta", "Pantalla", "Pantalón", "Pañal", "Pañuelo", "Papel", "Paquete",
  "Paraguas", "Para rayos", "Pared", "Partitura", "Pasaporte", "Pastel", "Patín", "Pedal", "Pegamento", "Peine",
  "Pelota", "Peluca", "Péndulo", "Peonza", "Pepino", "Pera", "Percha", "Periódico", "Perla", "Pesa",
  "Pesebre", "Piano", "Picaporte", "Pico", "Piedra", "Pijama", "Pilar", "Píldora", "Pincel",
  "Pingüino", "Pinza", "Piña", "Pipa", "Pirámide", "Piscina", "Pistola", "Pizarra", "Placa", "Plancha",
  "Planeta", "Planta", "Plástico", "Plata", "Plato", "Pluma", "Podio", "Polea", "Poltrona", "Pomo",
  "Pompa", "Pontón", "Portal", "Poste", "Potencia", "Pozo", "Prisma", "Proyector", "Puente", "Puerta",
  "Puerto", "Púlpito", "Pulsera", "Pupitre", "Radar", "Radio", "Raqueta", "Rascacielos", "Rastrillo", "Ratón",
  "Rayo", "Recipiente", "Red", "Reflector", "Regadera", "Regalo", "Regla", "Reloj", "Remolque", "Remo",
  "Repisa", "Resorte", "Retrato", "Revista", "Riel", "Rifle", "Roca", "Rodillo", "Rótulo", "Rueda",
  "Sable", "Saco", "Salero", "Salvavidas", "Sandalia", "Sandía", "Sartén", "Saxofón", "Sello", "Semáforo",
  "Semilla", "Seno", "Serrucho", "Servilleta", "Sextante", "Silla", "Sillón", "Silbato", "Sincrotrón", "Sinfonía",
  "Sirena", "Sobre", "Sofá", "Sombrero", "Sombrilla", "Sonda", "Soporte", "Soplete", "Sótano", "Sujetador",
  "Tabique", "Tabla", "Taburete", "Tacómetro", "Taladro", "Talla", "Tambor", "Tanque", "Tapa", "Tapiz",
  "Tapón", "Tarjeta", "Tarta", "Taza", "Teclado", "Techo", "Teja", "Tejido", "Tela", "Telar",
  "Teléfono", "Telescopio", "Televisor", "Telón", "Tenedor", "Tenaza", "Termómetro", "Termo", "Tesoro",
  "Tijeras", "Timbre", "Timón", "Tintero", "Tirachinas", "Tirante", "Título", "Toalla", "Tobogán", "Toldo",
  "Tomate", "Tornillo", "Torno", "Torre", "Traba", "Tractor", "Trampa", "Trampolín", "Transmisor", "Trapecio",
  "Trapo", "Tren", "Triángulo", "Trineo", "Trípode", "Trompeta", "Trono", "Trofeo", "Tubo", "Tuerca",
  "Tumba", "Túnel", "Turbina", "Uniforme", "Urna", "Vagón", "Vaina", "Vajilla", "Valija", "Válvula",
  "Vara", "Vaso", "Vela", "Velero", "Ventana", "Ventilador", "Vestido", "Vial", "Viga", "Violín",
  "Volante", "Xilófono", "Yate", "Yelmo", "Yunque", "Zanahoria", "Zapato", "Zócalo", "Zueco"
];
